version: '3.5'
services:
 unity:
  build:
    context: build
    args:
     ENVPATH: unity.env
  hostname: unity
  environment:
   - DISPLAY=${DISPLAY}
  volumes:
   - /tmp/.X11-unix:/tmp/.X11-unix
   - /lib/modules:/lib/modules
   - ~/unity:/opt/unity
  privileged: true
